name: "Create Release"

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Create Mod Archive
      run: |
        D=`pwd`
        D=`basename $D`
        cd ..
        zip -r $D.zip $D/manifest.json $D/LICENSE.txt $D/README.md $D/src $D/thirdparty $D/Archipelago/worlds/cavesofqud/data
    - name: Create APWorld
      run: |
        cd Archipelago/worlds
        zip -r ../../../cavesofqud.apworld cavesofqud
    # Currently not working due to missing file browser
    # - name: Generate Config Template
    #   run: |
    #     cd Archipelago
    #     find . -name "requirements.txt" -exec python -m pip install -r {} \;
    #     python Launcher.py "Generate Template Options"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "../*.zip,../*.apworld"
        # artifacts: "../*.zip,../*.apworld,./Archipelago/players/Templates/Caves of Qud.yaml"
        draft: true
        generateReleaseNotes: true