name: "Create Release"

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Create artifacts
      run: |
        make package
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*.zip,bin/*.apworld"
        draft: true
        generateReleaseNotes: true
